// Generated by CoffeeScript 1.4.0
(function() {
  var DEFAULTS, Settings;

  DEFAULTS = {};

  DEFAULTS[Util.KEYS.ZOOM_IN_KEY] = 'alt+=';

  DEFAULTS[Util.KEYS.ZOOM_OUT_KEY] = 'alt+-';

  DEFAULTS[Util.KEYS.ZOOM_RESET_KEY] = 'alt+0';

  Settings = (function() {

    function Settings(sendResponse) {
      this.sendResponse = sendResponse;
    }

    Settings.prototype.resetDefaults = function() {
      var key, keyName, _ref;
      _ref = Util.KEYS;
      for (keyName in _ref) {
        key = _ref[keyName];
        localStorage.removeItem(key);
      }
      return Util.defaultResponse(this.sendResponse);
    };

    Settings.prototype.key = function(keyName) {
      var _ref;
      return this.sendResponse({
        key: (_ref = Util.getFromLocalStorage(keyName)) != null ? _ref : DEFAULTS[keyName]
      });
    };

    Settings.prototype.saveKeys = function(newKeys) {
      var k, v;
      for (k in newKeys) {
        v = newKeys[k];
        Util.putInLocalStorage(k, v);
      }
      return Util.defaultResponse(this.sendResponse);
    };

    return Settings;

  })();

  chrome.extension.onMessage.addListener(function(req, sender, sendResponse) {
    var k, settings, v, _results;
    settings = new Settings(sendResponse);
    _results = [];
    for (k in req) {
      v = req[k];
      _results.push(settings[k](v));
    }
    return _results;
  });

}).call(this);
