// Generated by CoffeeScript 1.4.0
(function() {
  var DEFAULTS;

  DEFAULTS = {};

  DEFAULTS[Util.ZOOM_IN_KEY] = 'alt+=';

  DEFAULTS[Util.ZOOM_OUT_KEY] = 'alt+-';

  DEFAULTS[Util.ZOOM_RESET_KEY] = 'alt+0';

  chrome.extension.onMessage.addListener(function(req, sender, sendResponse) {
    var _ref;
    return sendResponse({
      key: (_ref = Util.getFromLocalStorage(req.key)) != null ? _ref : DEFAULTS[req.key]
    });
  });

}).call(this);
