// Generated by CoffeeScript 1.4.0
(function() {
  var addNotice, dom, setKeysFromBg;

  dom = {
    zoomInKeyInput: $('#zoomInKeyInput'),
    zoomOutKeyInput: $('#zoomOutKeyInput'),
    zoomResetKeyInput: $('#zoomResetKeyInput'),
    noticeBox: $('#noticeBox'),
    resetButton: $('#resetButton'),
    saveButton: $('#saveButton')
  };

  setKeysFromBg = function() {
    return _.each(util.KEYS, function(key) {
      return chrome.extension.sendMessage({
        key: key
      }, function(res) {
        return dom["" + key + "Input"].val(res.key);
      });
    });
  };

  addNotice = function(message) {
    var el;
    $('.notice').remove();
    el = $('<div>').addClass('notice').html("<span class=\"glyphicon glyphicon-floppy-saved\"></span> " + (_.escape(message)) + "\n<br />\nReload page to use new shortcuts");
    el.appendTo(dom.noticeBox);
    return el.delay(5000).fadeOut('slow', function() {
      return el.remove();
    });
  };

  dom.resetButton.click(function() {
    return chrome.extension.sendMessage({
      resetDefaults: true
    }, function(res) {
      setKeysFromBg();
      return addNotice('Shortcuts reset to defaults');
    });
  });

  dom.saveButton.click(function() {
    var key, newKey, newKeys, __, _ref;
    newKeys = {};
    _ref = util.KEYS;
    for (__ in _ref) {
      key = _ref[__];
      newKey = $.trim(dom["" + key + "Input"].val()).toLowerCase();
      if (newKey !== '') {
        newKeys[key] = newKey;
      }
    }
    return chrome.extension.sendMessage({
      saveKeys: newKeys
    }, function(res) {
      return addNotice('Settings have been saved');
    });
  });

  setKeysFromBg();

}).call(this);
