// Generated by CoffeeScript 1.4.0
(function() {
  var setKeysFromBg;

  setKeysFromBg = function() {
    return $.each(Util.KEYS, function(keyName, key) {
      return chrome.extension.sendMessage({
        key: key
      }, function(res) {
        return $("#" + key + "Input").val(res.key);
      });
    });
  };

  $(function() {
    $('#resetButton').click(function() {
      return chrome.extension.sendMessage({
        resetDefaults: true
      }, function(res) {
        return setKeysFromBg();
      });
    });
    $('#saveButton').click(function() {
      var key, keyName, newKey, newKeys, _ref;
      newKeys = {};
      _ref = Util.KEYS;
      for (keyName in _ref) {
        key = _ref[keyName];
        newKey = $.trim($("#" + key + "Input").val()).toLowerCase();
        if (newKey !== '') {
          newKeys[key] = newKey;
        }
      }
      $('.notice').remove();
      return chrome.extension.sendMessage({
        saveKeys: newKeys
      }, function(res) {
        $('#noticeBox').append("<div class='notice'>\n  <i class=\"icon-ok\"></i> Settings have been saved.\n  <br />\n  Reload page to use new shortcuts.\n</div>");
        return $('.notice').delay(5000).fadeOut('slow', function() {
          return $(this).remove();
        });
      });
    });
    return setKeysFromBg();
  });

}).call(this);
