// Generated by CoffeeScript 1.4.0
(function() {
  var dom, getCurrentZoomLevel;

  dom = {
    zoomInButton: $('.zoomInButton'),
    zoomOutButton: $('.zoomOutButton'),
    zoomResetButton: $('.zoomResetButton'),
    currentZoom: $('.currentZoom')
  };

  getCurrentZoomLevel = function() {
    return chrome.tabs.executeScript({
      code: "Util.getFromLocalStorage('zoomLevel');"
    }, function(data) {
      data = data[0] || 0;
      return dom.currentZoom.text("" + ((Math.round(data * 10) * 10 + 100).toFixed()) + "%");
    });
  };

  _.each(['in', 'out', 'reset'], function(type) {
    return dom["zoom" + (Util.capitalize(type)) + "Button"].click(function() {
      return chrome.extension.sendMessage({
        key: Util.KEYS["ZOOM_" + (type.toUpperCase()) + "_KEY"]
      }, function(res) {
        return chrome.tabs.executeScript({
          code: "Mousetrap.trigger('" + res.key + "');"
        }, function() {
          return getCurrentZoomLevel();
        });
      });
    });
  });

  getCurrentZoomLevel();

}).call(this);
