// Generated by CoffeeScript 1.4.0
(function() {
  var Util, root;

  Util = {
    ZOOM_IN_KEY: 'zoomInKey',
    ZOOM_OUT_KEY: 'zoomOutKey',
    ZOOM_RESET_KEY: 'zoomResetKey',
    getFromLocalStorage: function(key) {
      var value;
      value = localStorage[key];
      if (value) {
        return JSON.parse(value);
      }
      return null;
    },
    putInLocalStorage: function(key, value) {
      return localStorage[key] = JSON.stringify(value);
    }
  };

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Util = Util;

}).call(this);
