// Generated by CoffeeScript 1.4.0
(function() {
  var root, util;

  util = {
    KEYS: {
      ZOOM_IN_KEY: 'zoomInKey',
      ZOOM_OUT_KEY: 'zoomOutKey',
      ZOOM_RESET_KEY: 'zoomResetKey'
    },
    getFromLocalStorage: function(key) {
      var value;
      value = localStorage[key];
      if (value) {
        return JSON.parse(value);
      }
      return null;
    },
    putInLocalStorage: function(key, value) {
      return localStorage[key] = JSON.stringify(value);
    },
    defaultResponse: function(sendResponse) {
      return sendResponse({
        OK: true
      });
    },
    isBlank: function(str) {
      return !str || /^\s*$/.test(str);
    },
    capitalize: function(str) {
      return str.charAt(0).toUpperCase() + str.slice(1);
    }
  };

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.util = util;

}).call(this);
