// Generated by CoffeeScript 1.4.0
(function() {
  var ZOOM_LEVEL_KEY, addImportantStyle, changeFont, getKeyFromBackground, ignore, multiplyByRatio, totalRatio, zoomLevel;

  totalRatio = 1;

  ZOOM_LEVEL_KEY = 'zoomLevel';

  ignore = /SCRIPT|NOSCRIPT|LINK|BR|EMBED|IFRAME|IMG|VIDEO|CANVAS|STYLE/;

  $.extend($.gritter.options, {
    position: "bottom-left",
    fade_in_speed: 0,
    fade_out_speed: 0,
    time: 3000
  });

  multiplyByRatio = function(value, multiplier) {
    return (parseFloat(value) * multiplier) + 'px';
  };

  addImportantStyle = function(el, name, value) {
    return el.style.cssText += "" + name + ": " + value + " !important;";
  };

  changeFont = function(ratioDiff, notification) {
    var call, changeFontSizeCalls, element, multiplier, prevRatio, relevantElements, _fn, _i, _j, _len, _len1, _results;
    if (notification == null) {
      notification = true;
    }
    changeFontSizeCalls = [];
    prevRatio = totalRatio;
    totalRatio += ratioDiff;
    totalRatio = Math.round(totalRatio * 10) / 10;
    multiplier = totalRatio / prevRatio;
    relevantElements = $('body, body *');
    if (notification) {
      $('.gritter-close').click();
      $.gritter.add({
        title: "Text Zoom",
        text: "Level " + ((totalRatio * 100).toFixed()) + "%"
      });
    }
    if (totalRatio === 1) {
      relevantElements.css({
        'font-size': '',
        'line-height': ''
      });
      relevantElements.removeClass('noTransition');
      return Util.putInLocalStorage(ZOOM_LEVEL_KEY, false);
    }
    Util.putInLocalStorage(ZOOM_LEVEL_KEY, totalRatio - 1);
    if (prevRatio === 1) {
      relevantElements.addClass('noTransition');
    }
    _fn = function(el) {
      var currentLh, fontSize, lineHeight, tagName;
      tagName = el.tagName;
      if (tagName.match(ignore)) {
        return;
      }
      if (!Util.isBlank(el.innerText) || (tagName === 'TEXTAREA')) {
        currentLh = getComputedStyle(el).lineHeight;
        if (currentLh.indexOf('px') !== -1) {
          lineHeight = multiplyByRatio(currentLh, multiplier);
        }
      }
      fontSize = multiplyByRatio(getComputedStyle(el).fontSize, multiplier);
      return changeFontSizeCalls.push(function() {
        addImportantStyle(el, 'font-size', fontSize);
        if (lineHeight != null) {
          return addImportantStyle(el, 'line-height', lineHeight);
        }
      });
    };
    for (_i = 0, _len = relevantElements.length; _i < _len; _i++) {
      element = relevantElements[_i];
      _fn(element);
    }
    _results = [];
    for (_j = 0, _len1 = changeFontSizeCalls.length; _j < _len1; _j++) {
      call = changeFontSizeCalls[_j];
      _results.push(call());
    }
    return _results;
  };

  getKeyFromBackground = function(keyName, keyFunction) {
    return chrome.extension.sendMessage({
      key: keyName
    }, function(res) {
      return Mousetrap.bind(res.key, keyFunction);
    });
  };

  getKeyFromBackground(Util.KEYS.ZOOM_IN_KEY, function() {
    return changeFont(0.1);
  });

  getKeyFromBackground(Util.KEYS.ZOOM_OUT_KEY, function() {
    return changeFont(-0.1);
  });

  getKeyFromBackground(Util.KEYS.ZOOM_RESET_KEY, function() {
    totalRatio = 1;
    return changeFont(0);
  });

  zoomLevel = Util.getFromLocalStorage(ZOOM_LEVEL_KEY);

  if (zoomLevel) {
    changeFont(zoomLevel, false);
  }

}).call(this);
